# Generated by Django 4.0.6 on 2022-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtelegram',
            name='id_telegram',
            field=models.CharField(default='fff', max_length=100),
            preserve_default=False,
        ),
    ]
