# Generated by Django 4.0.6 on 2022-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
        ),
    ]
