# Generated by Django 4.0.6 on 2022-07-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='id_area',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.area'),
            preserve_default=False,
        ),
    ]
