# Generated by Django 4.0.6 on 2022-07-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_etapa_id_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
