# Generated by Django 4.0.6 on 2022-07-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_salida_oportunidades_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_Opcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id_Carta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etapa')),
                ('id_opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.opcion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
