# Generated by Django 4.0.6 on 2022-07-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ciclo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carta',
            old_name='id_etapa',
            new_name='etapa',
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='id_opcion',
            new_name='opcion',
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='carta',
            name='ciclo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.ciclo'),
            preserve_default=False,
        ),
    ]
