# Generated by Django 4.0.6 on 2022-07-19 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_rename_id_etapa_carta_etapa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carta',
            new_name='Nota',
        ),
    ]
