# Generated by Django 4.0.6 on 2022-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_id_carta_nota_id_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciclo',
            old_name='are',
            new_name='area',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='estado',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
