# Generated by Django 4.0.6 on 2022-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_are_ciclo_area_ciclo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciclo',
            old_name='estado',
            new_name='activo',
        ),
        migrations.AddField(
            model_name='etapa',
            name='activo',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
