# Generated by Django 4.0.6 on 2022-07-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_estado_ciclo_activo_etapa_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ciclo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.ciclo'),
            preserve_default=False,
        ),
    ]
