# Generated by Django 4.0.6 on 2022-07-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_etapa_ciclo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='AreaEmpresa',
        ),
        migrations.RenameModel(
            old_name='Ciclo',
            new_name='CicloArea',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
