# Generated by Django 4.0.6 on 2022-07-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_id_etapa_salida_etapa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidades',
            old_name='id_etapa',
            new_name='etapa',
        ),
        migrations.RenameField(
            model_name='oportunidades',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='oportunidades',
            name='cicloArea',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.cicloarea'),
            preserve_default=False,
        ),
    ]
