# Generated by Django 4.0.6 on 2022-07-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_entrada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
