# Generated by Django 4.0.6 on 2022-07-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_entrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa',
            old_name='id_area',
            new_name='area',
        ),
    ]
