# Generated by Django 4.0.6 on 2022-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_registrotrabajador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroTrabajador',
        ),
    ]
