# Generated by Django 4.0.6 on 2022-07-21 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_delete_registrotrabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTrabajador',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areaempresa')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
