# Generated by Django 4.0.6 on 2022-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_registrotrabajador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotrabajador',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='registrotrabajador',
            old_name='Empresa',
            new_name='empresa',
        ),
        migrations.AlterField(
            model_name='registrotrabajador',
            name='descripcion',
            field=models.TextField(max_length=160),
        ),
    ]
