# Generated by Django 4.0.6 on 2022-07-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_area_registrotrabajador_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotrabajador',
            name='empresa',
        ),
    ]
