# Generated by Django 4.0.6 on 2022-07-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_registrotrabajador_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotrabajador',
            old_name='area',
            new_name='id_area',
        ),
        migrations.RenameField(
            model_name='registrotrabajador',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
