# Generated by Django 4.0.6 on 2022-07-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_entrada_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidades',
            name='cicloArea',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='cicloArea',
        ),
        migrations.AlterField(
            model_name='oportunidades',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
