# Generated by Django 4.0.6 on 2022-08-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_oportunidades_cicloarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.areaempresa'),
            preserve_default=False,
        ),
    ]
