# Generated by Django 4.0.6 on 2022-08-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_entrada_id_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='id_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registrotrabajador'),
        ),
    ]
