# Generated by Django 4.0.6 on 2022-08-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_entrada_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidades',
            name='id_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.registrotrabajador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salida',
            name='id_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.registrotrabajador'),
            preserve_default=False,
        ),
    ]
