# Generated by Django 4.0.6 on 2022-08-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_oportunidades_id_area_salida_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
            preserve_default=False,
        ),
    ]
