# Generated by Django 4.0.6 on 2022-08-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_entrada_id_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id_empresa',
        ),
    ]
