# Generated by Django 4.0.6 on 2022-08-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_salida_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidades',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
