# Generated by Django 4.0.6 on 2022-09-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_oportunidades_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaempresa',
            name='calle',
            field=models.CharField(default='ffff', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaempresa',
            name='comuna',
            field=models.CharField(default='ffffff', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='calle',
            field=models.CharField(default='fffff', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='comuna',
            field=models.CharField(default='ffffff', max_length=150),
            preserve_default=False,
        ),
    ]
