# Generated by Django 4.0.6 on 2022-09-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_areaempresa_calle_areaempresa_comuna_empresa_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='ciclo',
        ),
        migrations.DeleteModel(
            name='CicloArea',
        ),
    ]
