# Generated by Django 4.0.6 on 2022-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_etapa_ciclo_delete_cicloarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaempresa',
            name='lat',
            field=models.IntegerField(default='222'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaempresa',
            name='long',
            field=models.IntegerField(default='222'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='lat',
            field=models.IntegerField(default='22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='long',
            field=models.IntegerField(default='222'),
            preserve_default=False,
        ),
    ]
