# Generated by Django 4.0.6 on 2022-09-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_areaempresa_lat_areaempresa_long_empresa_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotrabajador',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
