# Generated by Django 4.0.6 on 2022-09-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_rename_id_usuario_registrotrabajador_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotrabajador',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
