# Generated by Django 4.0.6 on 2022-09-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_rename_usuario_registrotrabajador_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotrabajador',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
