# Generated by Django 4.0.6 on 2022-09-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_rename_id_usuario_registrotrabajador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotrabajador',
            name='id_registro',
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='id',
            field=models.BigAutoField(auto_created=True, default=9999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
