# Generated by Django 4.0.6 on 2022-09-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_registrotrabajador_id_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='area',
        ),
    ]
