# Generated by Django 4.0.6 on 2022-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default='11111'),
            preserve_default=False,
        ),
    ]
