# Generated by Django 4.0.6 on 2022-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_telegram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
