# Generated by Django 4.0.6 on 2022-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usuario_id_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_telegram',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
